name: Build Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install the dependencies
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo "yovko93"

  ui-tests:
    runs-on: ubuntu-latest
    needs: build-unit-test
    
    steps:
        - name: Checkout the repo
          uses: actions/checkout@v4
        - name: Use Node.js version 20.x
          uses: actions/setup-node@v4
          with:
            node-version: 20.x
            cache: 'npm'
        - name: Install the dependencies
          run: npm install
        - name: Install Playwright browsers
          run: npx playwright install
        - name: Start the application
          run: npm start &
        - name: Run UI tests
          run: npm run test:ui
